### ISSUE TITLE
[shortcut window] improvement of the window size

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#105]
Probably we need a wider window for the last shortcut.

<img width="499" alt="screen shot 2018-12-11 at 13 35 46" src="https://user-images.githubusercontent.com/20819712/49780515-d141f200-fd49-11e8-8997-6ab739b2e5c3.png">

**Comment by veggiesaurus** [comment]
@kswang1029 I can't reproduce that. Is that the desktop or the browser? What window size and DPI are you using? Mine looks like below
![image](https://user-images.githubusercontent.com/592504/49788795-f414dc00-fd32-11e8-9846-4847cf34c221.png)

**Comment by kswang1029** [comment]
It is desktop version at http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta1b.dmg

And tested with MacBook Pro 13" (2560 x 1600) dpi=227.

**Comment by veggiesaurus** [comment]
I see the issue now. The dialog is rendered differently when brought up from menu and from the shortcut (shift + ?)

**Comment by kswang1029** [comment]
Aha!
