### ISSUE TITLE
[imageviewer+animator] aspect ratio tip

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#112]
When two images are opened (append) and are switched in between using "frame" in animator, we see the aspect ratio tip then it goes away. This becomes an issue when using the animator to do blinking as the tip does not go away and block the view. Issue reported by @arusstaylor

**Comment by kswang1029** [comment]
@veggiesaurus maybe we can have a button to enable/disable the aspect ratio tip (with default off)?

**Comment by veggiesaurus** [comment]
Due to how I've implemented the aspect ratio tip, it will show up whenever the frame is changed. I'll fix this to only show up when (a) loading a file for the first time or (b) changing the view size.

**Comment by kswang1029** [comment]
Thanks. Sorry not being thinking of this use case.
