### ISSUE TITLE
raster rendering in animation

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#16]
during the animation, the boundary values for color mapping seem to be locked to the frame just before the start of animation so that some frames are all white (saturated). 

During the animation, the per-frame histogram is not updated accordingly. 

UPDATE: if fps is low (e.g., 1 fps with good internet speed, histogram does update and raster rendering works as normal)

Demo: https://youtu.be/JmalQwCPC5A

**Comment by veggiesaurus** [comment]
fixed in #32
