### ISSUE TITLE
animator: redundant channel index

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#18]
when viewing a cube with a small number of channels, some redundant indices show up as shown in the attached image. Note that the Stokes axis does not have this issue.

![screen shot 2018-09-05 at 11 05 04](https://user-images.githubusercontent.com/20819712/45068894-5dfe6380-b0fc-11e8-98d1-6323af538702.png)

**Comment by veggiesaurus** [comment]
I'm able to reproduce this with a 4 channel file. Working on a fix now
