### ISSUE TITLE
imageViewer cursor

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#36]
imageViewer:
- Need to show velocity, frequency, and Stokes of the current frame somewhere (integrated in the cursor info bar, maybe?). 
Format for velocity is like "**%.3f km/s, LSRK / Radio, Q**". Here "LSRK" can be read  from the header keyword "SPECSYS", while "Radio" can be read from the header keyword "VELREF". "Q" indicates the Stokes parameter of the current frame. Format for frequency is like "**%.3f MHz, LSRK, Q**", where "LSRK" can be read  from the header keyword "SPECSYS"
- as more information is shown in the cursor info bar, we may need a two-line bar by default.

**Comment by veggiesaurus** [comment]
@kswang1029 splitting this into two separate issues. @confluence will handle the AST config options.

**Comment by veggiesaurus** [comment]
almost complete, just requires hi-dpi adjustments

**Comment by veggiesaurus** [comment]
fixed in #65

**Comment by veggiesaurus** [comment]
@kswang1029 are you happy with the functionality in PR #91 in terms of this issue? For post-V1, we can add automatic precision and reference frame conversion.

**Comment by kswang1029** [comment]
Yes. The frequency/velocity display in the cursor info bar works well. Tested all possible frames that casa can transform. Compared with casaviewer which supports a subset of frames and results are consistent.
