### ISSUE TITLE
Line plot enhancements

### ISSUE THREAD

**Issue by veggiesaurus** [idia-astro/carta-frontend#37]
There are a number of enhancements that the line plot component needs:

- [x] Zooming in Y and XY
- [x] Horizontal markers (e.g. for mean values)
- [x] Rectangular markers (non-interactive) (e.g. for RMS indicator)
- [x] Optional callback for tick formatting
- [x] Options for showing/hiding X and Y labels
- [x] Line/point options for data

**Comment by arusstaylor** [comment]
I might add 

 - visual and numeric display of data mean and rms, a la cyberSKA.
 - select line or point symbol representation of the data

Russ

**Comment by veggiesaurus** [comment]
@arusstaylor I think data mean can be displayed as a simple horizontal line, right? How should RMS be displayed?

**Comment by arusstaylor** [comment]
You should check out cyberSKA profiles.   The mean was represented by a line and the rms upper and lower bounds are represented by a light shaded region.  Go to a profile in cyberSKA click on the little cog wheel in the profile window to turn on the option.

Russ

**Comment by veggiesaurus** [comment]
@arusstaylor Yes, the CyberSKA profiles were the only example I could think of. I agree that RMS bounds should be a lightly shaded region.

**Comment by arusstaylor** [comment]
I think this is unique to the cyberSKA viewer.
Russ

**Comment by veggiesaurus** [comment]
@kswang1029 for reference, this is what Russ is referring to: 
![image](https://user-images.githubusercontent.com/592504/46200640-72580980-c312-11e8-8a59-617b16acda73.png)

**Comment by kswang1029** [comment]
> @kswang1029 for reference, this is what Russ is referring to:
> ![image](https://user-images.githubusercontent.com/592504/46200640-72580980-c312-11e8-8a59-617b16acda73.png)

Right, marking the rms as a shaded region is a good idea and useful for analysis. I guess how the rms is derived is another question. 

For the z-profiler, we will also need a label capability so that possible molecular transitions (from the online database) can be marked directly on the plot (one of the sci-req). The label could be a vertical bar with a text string rotated by 90 degrees.

**Comment by veggiesaurus** [comment]
@arusstaylor for mean and RMS calculations, is it the mean/RMS of the entire profile, or just the part of the profile that you're currently looking at? For example, if I zoom in on a particular section of the profile, should it re-calculate the mean and RMS for the section?

**Comment by veggiesaurus** [comment]
@arusstaylor @kswang1029 in general, this makes sense, along with the range of the spatial profile matching the image view's field of view. However, this is for cursor profiles, specifically. For profiles related to other point regions, I don't think they should adjust to match the field of view.

**Comment by kswang1029** [comment]
is the mean/rms automatically determined by using the data in the current viewing range? or full range? Either one I cannot imagine good use cases. Maybe it is better to let the users select which data are used for the mean/rms calculations by making a box with cursor. Then the shaded region is plotted and users can use that as a reference to inspect which features are above 3-sigma threshold. If it is automatically determined by the viewing range, usually there are unwanted data for the mean/rms calculations.

**Comment by veggiesaurus** [comment]
> Maybe it is better to let the users select which data are used for the mean/rms calculations by making a box with cursor.

I like this idea. I believe we will need to do something similar with curve fitting, because it will require us to "freeze" the data and export it to another widget for fitting. Needs careful consideration in terms of UI though

**Comment by kswang1029** [comment]
Right, for gaussian fitting for example, users may draw some boxes first to provide initial gauss of fitting parameters (number of gaussians, amplitude, center, FWHM width, x-ranges, etc.).

Agreed, need careful design of UI for best UX

**Comment by arusstaylor** [comment]
Hi Angus.

Trying out the latest version of the viewer.  A couple of comments on the profile window.

1)  The actual mean and rms should be displayed as number somewhere when this option is turned on.  
2)  In the setup menu “draw as points” is set up as a on-off toggle.   Not sure if this is a the best approach.  I think we want at least three options for display: Histogram, points, joint to dots.  These are mutually incomparable options, so should we rather have selection boxes for the options one wants?

Russ

**Comment by veggiesaurus** [comment]
> The actual mean and rms should be displayed as number somewhere when this option is turned on. 

Agreed. This will be integrated into a separate feature, because we also need to display the cursor value in a similar fashion. I'll create an issue for it. 

> In the setup menu “draw as points” is set up as a on-off toggle.   Not sure if this is a the best approach.  I think we want at least three options for display: Histogram, points, joint to dots

A dropdown box or a button group for this would work. I'll add an issue for this as well

**Comment by arusstaylor** [comment]
When you append a frame, it would be cool if the different frames appeared as tabs in the main image canvas, and click on the tab brought frame and associated profile. This provides an intuitive one-click way to change image frames  


I have gotten into a state where the x-profile is not showing the data in the zoomed image region,  The y-profile is correctly showing the zoomed image data but the x-profile is showing the full data set. 


Russ

**Comment by veggiesaurus** [comment]
> I have gotten into a state where the x-profile is not showing the data in the zoomed image region, The y-profile is correctly showing the zoomed image data but the x-profile is showing the full data set. Russ

Did you zoom in/out on the x-profile? The default behaviour is to auto-scale to match the image view unless you zoom in or out on the image. You can double-click to go back to the default range

**Comment by arusstaylor** [comment]
The z-profile plot should how a red vertical line at the position of the channel being viewed in the image canvas, in the same way the x and y profiles show the ordinate of the cursor in x and y.

x, y and z profiles should all have the same behaviour.  When we get to the point of viewing rotated cubes z will be one of the image plane coordinates.

Russ

**Comment by arusstaylor** [comment]
Please ignore. I see that this is already in place. I was displaying channel 0 and could not see the red line.

Russ
