### ISSUE TITLE
odd behavior of left/right click in the histogram of renderConfig

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#41]
The video shows this odd behavior.
https://www.youtube.com/watch?v=774bXm-IXlM

The test is done with the dev-viewer, chrome, and MacBook Pro using track pad. Frontend version = 933a9e0
The beginning of the video demonstrates that the pointing of the track pad should work precisely. But while clicking on the histogram, the min red line doesn't update to the position where left-click is issued.

Also tested with iMac using Magic Mouse, it works properly...

**Comment by veggiesaurus** [comment]
fixed in #42
