### ISSUE TITLE
default image position in the imageViewer is off by half pixel (should just fill the view)

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#45]
This issue becomes prominent when viewing small images, as demonstrated by the attached images.
![screen shot 2018-10-17 at 12 44 01 pm](https://user-images.githubusercontent.com/20819712/47062811-c2880480-d20a-11e8-99a9-c798922b4e40.png)
![screen shot 2018-10-17 at 12 43 13 pm](https://user-images.githubusercontent.com/20819712/47062812-c2880480-d20a-11e8-943e-9ee13878a337.png)

**Comment by veggiesaurus** [comment]
@kswang1029 fixed in #77, can you test (also updated on dev-viewer)

**Comment by kswang1029** [comment]
Thanks. Verified. 👍
