### ISSUE TITLE
AST config: coordinate systems when multiple frames exist

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#50]
The coordinate system should remain the same when new image is loaded as new frame.
To reproduce: 
1) open orion_12co_hera.hdf5
2) open supermosaic.10.hdf5 as new frame
3) use animator to switch back to orion
4) check the gridline 
<img width="817" alt="screen shot 2018-10-18 at 20 38 28" src="https://user-images.githubusercontent.com/20819712/47155068-8f329c00-d316-11e8-80a0-1b3ac1fbec35.png">

<img width="817" alt="screen shot 2018-10-18 at 20 39 00" src="https://user-images.githubusercontent.com/20819712/47155067-8f329c00-d316-11e8-9c62-007bf01a4887.png">

**Comment by confluence** [comment]
This has been fixed in my branch.
