### ISSUE TITLE
AST options: grid -> custom gap

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#54]
frontend version: b9e44e2
In overlay setting/grid, if custom gap is toggled, the coordinate grid is disappeared.

**Comment by veggiesaurus** [comment]
@kswang1029 So this is a tricky one. The "gap" value is in the units of the current file. So if the current file is in degrees, then the gap will be in degrees, and so on. 

When you select "custom gap", the gap value is set from the value in the numeric input below. Depending on the FOV of the image viewer, this value may or may not be sensible, but it's difficult to choose a starting value that works for all images. 

In my mind, that's not a huge problem, but could probably be explained more clearly to the user. What *is* a problem is that AST throws an error when the gap size is too large for any grid lines to be drawn, and that prevents the rest of the AST overlay from being shown. @confluence , I think that's what we should attempt to fix in the short term.

**Comment by confluence** [comment]
Fixed in my branch.

**Comment by veggiesaurus** [comment]
this now behaves correctly. No grid is drawn if the gaps are too large, but the rest of the AST overlay still gets rendered correctly.
