### ISSUE TITLE
Improve graph type options

### ISSUE THREAD

**Issue by veggiesaurus** [idia-astro/carta-frontend#57]
Current plot options for displaying a stepped graph (histogram), point cloud or line graph are needlessly complicated. The two options "draw as points" and "interpolated" should be replaced by a single dropdown or a button group. 

Suggested nomenclature for the three options: "Stepped", "Points", "Curve" (or "Line")

**Comment by veggiesaurus** [comment]
@arusstaylor second issue based on your comment. I'm hesitant to use "histogram" to describe the stepped plot, since, in the case of both the spatial and spectral profiler, they're _not_ actually histograms. Join-the-dots is also not a particularly widely used term, so I'd opt for either "Curve" or "Line" to describe the plot type.

**Comment by arusstaylor** [comment]
Agreed.  
Russ

**Comment by veggiesaurus** [comment]
closed in #60
