### ISSUE TITLE
[improvement] channel index in animator

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#68]
The channel indices in the animator collide when the panel is narrow and the total number of channels is too large. Attached is an example viewing a cube with a 7680-channel cube on my laptop.
<img width="572" alt="screen shot 2018-10-24 at 12 32 34" src="https://user-images.githubusercontent.com/20819712/47406539-66346000-d789-11e8-8249-05db041b1755.png">

Perhaps we can improve this by just showing the first and the last channel indices. Users can estimate where to click to jump to a certain channel with the help of the channel index below the slider. 
Or, the indices can be generated in a more smart way with the consideration of the widget width.

**Comment by veggiesaurus** [comment]
adjusting for the widget width would be first prize. However, that's quite tricky, as we'd need to measure (a) the widget width and (b) the width of each tick label. 

We could just show first and last channels, that would look ok. Perhaps the best way is to adjust the step size until we get a total of between 3 and 5 labels?

**Comment by kswang1029** [comment]
Yes, showing just few representative labels would provide better UX than showing just the boundary two.

**Comment by veggiesaurus** [comment]
My initial suggestion was to try to find "nice" values for the tick intervals (10, 20, 50, etc). However, I think it's more important to show the first and last channels correctly (as well as ticks in between). I propose the following:

1) If an image has < 10 channels, show the channels themselves as ticks
2) If an image has more, display 5 ticks in total, with the tick interval calculated such that the first and last tick will always be shown. (This is similar to how DS9 approaches it)

**Comment by kswang1029** [comment]
Sounds a good idea and should provide good UX.
