### ISSUE TITLE
[imageViewer] pan at high zoom level

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#70]
frontend version: f6daeb9
It appears that the click-to-center pan action suffers from probably hi-dpi issue (found this with my MBP).
Below is before clicking the orange pixel.
<img width="816" alt="screen shot 2018-10-25 at 08 08 38" src="https://user-images.githubusercontent.com/20819712/47468409-bb29b200-d82d-11e8-912d-b0d21f7ec9b3.png">
We expect to see the orange pixel is centered to the axis border box. But we see
<img width="815" alt="screen shot 2018-10-25 at 08 08 52" src="https://user-images.githubusercontent.com/20819712/47468428-d3013600-d82d-11e8-99b4-e744f778cff2.png">
The position is off. And even higher zoom level, the offset is much prominent. 

I am not sure if zoom using a hi-dpi screen has similar issue. Could you have a look too?

**Comment by veggiesaurus** [comment]
@kswang1029 fixed in #76, can you verify (build updated on dev-viewer)

**Comment by kswang1029** [comment]
Verified. 👍
