### ISSUE TITLE
[cursor-xy-profiler] pixel rounding issue 

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#72]
frontend version: f6daeb9, tested with MBP

Only the first quadrant of a pixel provides correct both frontend and backend profiles. Others do not.
<img width="813" alt="screen shot 2018-10-25 at 09 36 23" src="https://user-images.githubusercontent.com/20819712/47470973-c931ff80-d83a-11e8-927b-160acd4be2ed.png">

**Comment by veggiesaurus** [comment]
I think this cropped up when we moved from the bottom left of the bottom left pixel being (0,0) to the center of the bottom left pixel being (0,0)

**Comment by kswang1029** [comment]
Yes, it is the exact issue. Just want to make sure this is solved in the release version in the near future.
