### ISSUE TITLE
[cursor freeze] position offset of the cross

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#90]
This is seen in the "desktop" version. When pressing shift+space to place the cross, sometimes there is an position offset between the cross and the cursor position. This is not seen in the server version with chrome. 

testing app: http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-ASIAA-1-Dec-2018.dmg (with electron 4.0.0)

*update*: the desktop version seems to place the cross at the pixel center of the pixel pointed by the cursor, not right at the cursor position.

**Comment by veggiesaurus** [comment]
So it's probably converting the pixel coordinates to ints?

**Comment by kswang1029** [comment]
likely, yes.
