### ISSUE TITLE
[xy(z) profiler] steps plot

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-frontend#92]
In the xyz profile plots, it seems that the step is aligned to the left edge, not center. Naively aligning to the center is better. Any thoughts? 

![screen shot 2018-12-05 at 3 25 59 pm](https://user-images.githubusercontent.com/20819712/49497175-af0c2800-f8a2-11e8-8ea7-ba3439801e09.png)

**Comment by veggiesaurus** [comment]
agreed, the steps should be centred on the pixel values, to make them consistent with our plot

**Comment by veggiesaurus** [comment]
@kswang1029 I will work on a feature for the ChartJS library and issue a PR to that repo, hopefully it will get merged in quickly.

**Comment by kswang1029** [comment]
Ok thanks for fixing this.

**Comment by veggiesaurus** [comment]
PR to the Chart.JS library has been [submitted](https://github.com/chartjs/Chart.js/pull/5908). It might take some time to be merged into the master branch and released, so if this is an urgent fix, we will need to manually use the updated build (requires a bit of re-configuration). @kswang1029 thoughts?

**Comment by veggiesaurus** [comment]
@kswang1029 turns out it was very easy to use the updated build, so I've issued a PR (#110). Can you have a look at dev-viewer to confirm if it looks ok?

**Comment by kswang1029** [comment]
it looks GREAT!
